variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

stages: 
  - test
  - release
  - publish

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci/python:3.7
  before_script:
  - pipenv install --dev

lint:
  stage: test
  tags:
    - wopr
  script:
    - pipenv run pylint --rcfile=.pylintrc src
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

test:
  stage: test
  tags:
    - wopr
  script:
    - pipenv run python -m pytest --cov-report term:skip-covered --cov src/ tests/
  coverage: '/TOTAL.*\s+(\d+%)$/'

publish-stable:
  stage: publish
  tags:
    - wopr
  script:
    - pipenv run python setup.py sdist bdist_wheel
    - pipenv run twine upload -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.wopr.inf.mdc/repository/pypi-stable/ dist/*
    - pipenv run twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --repository-url https://upload.pypi.org/legacy/ dist/*
  only:
    refs:
    - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-unstable:
  stage: publish
  tags:
    - wopr
  script:
    - pipenv run python setup.py sdist bdist_wheel
    - pipenv run twine upload -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.wopr.inf.mdc/repository/pypi-unstable/ dist/*
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  image: registry.mdcatapult.io/informatics/docker-images/ci/python:3.7
  tags:
    - wopr
  before_script:
    - ''
  script:
    - /scripts/release.sh src --commits
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
