variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

stages: 
  - test
  - release
  - publish

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci:python
  before_script:
  - pipenv install --dev
  - pipenv shell

lint:
  stage: test
  tags:
    - wopr
  script:
    - pylint --rcfile=.pylintrc src
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

test:
  stage: test
  tags:
    - wopr
  script:
    - python -m pytest --cov-report term:skip-covered --cov src/ tests/
  coverage: '/TOTAL.*\s+(\d+%)$/'

publish-stable:
  stage: publish
  tags:
    - wopr
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.mdcatapult.io/repository/pypi-stable/ dist/*
  only:
    refs:
    - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-unstable:
  stage: publish
  tags:
    - wopr
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.mdcatapult.io/repository/pypi-unstable/ dist/*
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  image: registry.mdcatapult.io/informatics/docker-images/ci:python
  tags:
    - wopr
  before_script:
    - ''
  script:
    - /scripts/release.sh src --commits
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
