variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

stages: 
  - test
  - release
  - publish

default:
  image: registry.gitlab.com/medicines-discovery-catapult/informatics/docker-images/ci/python:3.7
  before_script:
  - pipenv install --dev

lint:
  stage: test
  script:
    - pipenv run pylint --rcfile=.pylintrc src
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

test:
  stage: test
  script:
    - pipenv run python -m pytest --cov-report term:skip-covered --cov src/ tests/
  coverage: '/TOTAL.*\s+(\d+%)$/'

publish-stable:
  stage: publish
  script:
    - pipenv run python setup.py sdist bdist_wheel
    - pipenv run twine upload -u gitlab-ci-token -p $CI_TOKEN --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/* 
    - pipenv run twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --repository-url https://upload.pypi.org/legacy/ dist/*
  only:
    refs:
    - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-unstable:
  stage: publish
  script:
    - pipenv run python setup.py sdist bdist_wheel
    - pipenv run twine upload -u gitlab-ci-token -p $CI_TOKEN repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi-unstable dist/*
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  before_script:
    - ''
  script:
    - /scripts/release.sh src --commits
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
